name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-repo-info:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Update Repository Description
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: gerrymoeis
          REPO_NAME: hitam-putih
        run: |
          # Install GitHub CLI if not already installed
          if ! command -v gh &> /dev/null; then
            echo "Installing GitHub CLI..."
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
          fi
          
          # Set repository description
          DESCRIPTION="Hitam Putih - Aplikasi konversi gambar ke hitam putih (grayscale) yang sederhana dan mudah digunakan."
          echo "Setting repository description to: $DESCRIPTION"
          gh repo edit "$REPO_OWNER/$REPO_NAME" --description "$DESCRIPTION"
          
          # Set repository topics
          TOPICS="flutter,dart,image-processing,black-and-white,grayscale,android,mobile-app"
          echo "Setting repository topics to: $TOPICS"
          gh repo edit "$REPO_OWNER/$REPO_NAME" --add-topic "$TOPICS"
  
  build:
    runs-on: ubuntu-latest
    needs: update-repo-info
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2'
          channel: 'stable'
          # Using the same Flutter version as specified in the project
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Analyze project source
        run: flutter analyze
      
      - name: Run tests
        run: flutter test
      
      - name: Build APK
        run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
